sudo: required
services:
  - docker

before_install:
  - docker build -t brijesh .

script:
        - docker run -e CI=true -p 80:3000  brijesh:latest npm run test -- --coverage

          #after_success:
  #log in to docker CLI
  #  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take built images and push to DOcker hub
  #  - docker push brijesh

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-532163291253"
  bucket_path: "docker"
  on:
    branch: master
  access_key: $AWS_ACCESS_KEY
  secret_key:  $AWS_SECRET_KEY

