language: generic
sudo: required
services:
    - docker

# Build testing container
before_install:
    - docker build -t brijesh -f Dockerfile.dev  .

# Run Tests
script:
        - docker run -e CI=true -p 80:3000  brijesh:latest npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker1"
    env: "Docker1-env"
    bucket_name: "elasticbeanstalk-ap-south-1-532163291253"
    bucket_path: "docker1"
    on:
      branch: master
    access_key_id: $access_key
    secret_access_key: $secret_key
